server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: tones-service
          uri: lb://tones-service
          predicates:
          - Path=/tones/**
          filters:
          - RewritePath=/tones/(?<path>.*), /$\{path}
        - id: melodies-service
          uri: lb://melodies-service
          predicates:
          - Path=/melodies/**
          filters:
          - RewritePath=/melodies/(?<path>.*), /$\{path}


       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        